### ISSUE TITLE
引入color-picker扩展后，将会导致无法利用setState设置editorState来更新编辑器的内容

### ISSUE THREAD

**Issue by baby1990** [margox/braft-extensions#1]
问题：加入color-picker扩展后，利用this.setState修改editorState的值，该状态会更新，但是编辑器的内容无法成功按照更新后的editorState的值渲染出来，但是编辑器内修改编辑器内容可以更新editorState的值，也就是数据流变成了单向

**Comment by margox** [comment]
已确认，晚上会发布修复版本

**Comment by margox** [comment]
braft-editor更新到2.1.19试试
