### ISSUE TITLE
code-highlighter: theme was preserved in the codeblock by copy code from IDE(vscode)

### ISSUE THREAD

**Issue by sukechris** [margox/braft-extensions#10]
Hi, thanks for your great work, I have a problem with extension of code-highlighter. when I insert my code from my IDE(vscode) by copy (`control`/`command` + `C` )，and the theme of my IDE was preserved in the codeblock of braft-editor.

here is, the theme of code is my IDE's theme, and the code style will be preserved in the html string, when I call `this.state.editorState.toHTML()`
![image](https://user-images.githubusercontent.com/36565253/50557124-ef818900-0d1c-11e9-84b8-64d99a423574.png)

however, the braft-editor code-highlighter default theme is `prism-tomorrow`, and the expected result is:
![image](https://user-images.githubusercontent.com/36565253/50557192-cf05fe80-0d1d-11e9-9957-6cef8a7998a6.png)

**Comment by margox** [comment]
hi, a simple way to resolve your problem is using the prop `stripPastedStyles`, just like this:
```jsx
<BraftEditor stripPastedStyles={true} />
```
and a more advanced way is to use a extend control button to control this prop.:
```jsx
class Demo extends React.Component {

  constructor(props) {

    super(props)

    this.state = {
      stripPastedStyles: false
    }

  }

  toggleStripPastedStyles = () => {
    this.setState({
      stripPastedStyles: !this.state.stripPastedStyles
    })
  }

  render() {

    const { stripPastedStyles } = this.state

    return (
      <BraftEditor
        extendControls={[{
          key: 'toggle-strip-pasted-styles',
          type: 'button',
          text: `Paste as plain text: ${stripPastedStyles ? 'ON' : 'OFF'}`,
          onClick: this.toggleStripPastedStyles
        }]}
        stripPastedStyles={stripPastedStyles}
      />
    )

  }

}
```

**Comment by sukechris** [comment]
@margox thank you!, it solved my problem
