### ISSUE TITLE
mentions 样式问题

### ISSUE THREAD

**Issue by gtt011029** [margox/braft-extensions#138]
按照Demo写的mention， 样式有问题， 引入了import 'braft-extensions/dist/emoticon.css';

![image](https://user-images.githubusercontent.com/45391413/192251976-986952af-f19e-4b05-a618-f818f133351e.png)

**Comment by gtt011029** [comment]
自问自答：使用braft.js 里面的样式

**Comment by xiaohan759** [comment]
你好？请问你怎么解决的，能看看代码吗？ @gtt011029

**Comment by gtt011029** [comment]
@xiaohan759    使用这个Custom Themed Mention Example  例子里面的样式
![image](https://user-images.githubusercontent.com/45391413/204759348-e656891e-fbf7-452b-bd83-9ba30462c7ca.png)

**Comment by gtt011029** [comment]
> 你好？请问你怎么解决的，能看看代码吗？ @gtt011029
