### ISSUE TITLE
多个table单元格内容文本被选中时，在输入内容时，会导致单元格被误删

### ISSUE THREAD

**Issue by shenzhim** [margox/braft-extensions#14]

**Comment by margox** [comment]
https://github.com/margox/braft-extensions/blob/master/src/table/handlers.js#L26 按理说这一行的判断，会组断掉多个单元格被选中时候的删除操作，帮忙看一下为什么没有进入到这个判断里面来？

**Comment by shenzhim** [comment]
借助 handleBeforeInput 事件来处理这个场景，稍后提个pr
