### ISSUE TITLE
编辑器里新添加表格没有问题，但是编辑 有表格 的内容时，表格没有正确显示

### ISSUE THREAD

**Issue by liangyongrui** [margox/braft-extensions#22]
编辑器里新添加表格没有问题，但是编辑 有表格 的内容时，表格没有正确显示

已经按照https://github.com/margox/braft-extensions/blob/master/README.md#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9增加了id

 "braft-editor": "^2.2.9",
 "braft-extensions": "0.0.18",

**Comment by margox** [comment]
贴一下你的代码看看？

**Comment by liangyongrui** [comment]
在项目根组件的开头写了
`  BraftEditor.use(Table({
    withDropdown: true,
    includeEditors: ['editor-1']
  }))`

![image](https://user-images.githubusercontent.com/24314057/55318981-87227f00-54a6-11e9-9a55-54eb5299d0fe.png)

我点击确定后，输出
    console.log(editorState.toHTML(), "############")
`<p></p><p></p><p></p><table ><tr><td colSpan="1" rowSpan="1">1</td><td colSpan="1" rowSpan="1">2</td></tr><tr><td colSpan="1" rowSpan="1">3</td><td colSpan="1" rowSpan="1">4</td></tr></table><p></p> ############`

再打开：
![image](https://user-images.githubusercontent.com/24314057/55319067-b5a05a00-54a6-11e9-92d0-b0d2e67753a0.png)


完整的代码：
`// @ts-ignore
import {Button, Modal} from '@hi-ui/hiui/es'
import React, {useEffect, useState} from 'react'
import 'braft-editor/dist/index.css'
import {updateGraph} from '../../index'
import BraftEditor from 'braft-editor'
// @ts-ignore
import '../../style/processInput.scss'
import 'braft-extensions/dist/table.css'

export default function RichTextInput(props: InputProps) {
  const {attr, value, onBlurFunction, updateAttributes} = props

  const [editorState, setEditorState] = useState(BraftEditor.createEditorState(value || "", {editorId: 'editor-1'}))
  const [content, setContent] = useState(editorState.toText())
  const [rawContent, setRawContent] = useState(value)
  const [modalShow, setModalShow] = useState(false)

  const showContent = content && content.length > 20 ? content.substring(0, 15) + '...' : content

  useEffect(() => {
    setEditorState(BraftEditor.createEditorState(value))
    setContent(editorState.toText())
    setModalShow(false)
  }, [value])


  function update() {
    console.log(editorState.toHTML(), "############")
    if (onBlurFunction) {
      onBlurFunction(attr, editorState.toHTML(), updateAttributes)
    } else {
      updateGraph(attr, editorState.toHTML(), updateAttributes)
    }
    setRawContent(editorState.toHTML())
    setContent(editorState.toText())
    setModalShow(false)
  }


  function showModal() {
    setEditorState(BraftEditor.createEditorState(rawContent))
    setModalShow(true)
  }

  return <div>
    <Button type='default' clasName={"processInput"} style={{width: '180px', display: 'block'}}
            onClick={showModal}>{showContent}</Button>
    <Modal title='编辑文本' width='1000px' show={modalShow}
           onCancel={() => setModalShow(false)}
           onConfirm={update}>
      <BraftEditor value={editorState} id="editor-1" onChange={setEditorState}/>
    </Modal>
  </div>
}`

**Comment by margox** [comment]
```js
function showModal() {
    setEditorState(BraftEditor.createEditorState(rawContent))
    setModalShow(true)
}
```
是不是上面这个地方没有传editorId导致的？你试试把所有和id相关的都去掉试试

**Comment by liangyongrui** [comment]
> ```js
> function showModal() {
>     setEditorState(BraftEditor.createEditorState(rawContent))
>     setModalShow(true)
> }
> ```
> 
> 是不是上面这个地方没有传editorId导致的？你试试把所有和id相关的都去掉试试

对，不好意思漏改了一个地方，就是这里导致的。

十分感谢～

**Comment by themeth** [comment]
> 
> 
> > ```js
> > function showModal() {
> >     setEditorState(BraftEditor.createEditorState(rawContent))
> >     setModalShow(true)
> > }
> > ```
> > 
> > 
> > 是不是上面这个地方没有传editorId导致的？你试试把所有和id相关的都去掉试试
> 
> 对，不好意思漏改了一个地方，就是这里导致的。
> 
> 十分感谢～

你好，遇到同样问题，请问修改哪个地方正常

**Comment by themeth** [comment]
> 
> 
> > > ```js
> > > function showModal() {
> > >     setEditorState(BraftEditor.createEditorState(rawContent))
> > >     setModalShow(true)
> > > }
> > > ```
> > > 
> > > 
> > > 是不是上面这个地方没有传editorId导致的？你试试把所有和id相关的都去掉试试
> > 
> > 
> > 对，不好意思漏改了一个地方，就是这里导致的。
> > 十分感谢～
> 
> 你好，遇到同样问题，请问修改哪个地方正常

搞定。
如果在使用扩展模块时，指定了includeEditors或excludeEditors属性，则通过BraftEditor.createEditorState创建初始化内的时候，需要传入一个editorId属性来指明创建的editorState是给哪个BraftEditor组件用的：
`// 使用BraftEditor.createEditorState创建编辑器数据
const initialValue = BraftEditor.createEditorState('xxxxxx', { editorId: 'editor-1' })`

**Comment by szhero** [comment]
> > > > ```js
> > > > function showModal() {
> > > >     setEditorState(BraftEditor.createEditorState(rawContent))
> > > >     setModalShow(true)
> > > > }
> > > > ```
> > > > 
> > > > 
> > > > 是不是上面这个地方没有传editorId导致的？你试试把所有和id相关的都去掉试试
> > > 
> > > 
> > > 对，不好意思漏改了一个地方，就是这里导致的。
> > > 十分感谢～
> > 
> > 
> > 你好，遇到同样问题，请问修改哪个地方正常
> 
> 搞定。
> 如果在使用扩展模块时，指定了includeEditors或excludeEditors属性，则通过BraftEditor.createEditorState创建初始化内的时候，需要传入一个editorId属性来指明创建的editorState是给哪个BraftEditor组件用的：
> `// 使用BraftEditor.createEditorState创建编辑器数据 const initialValue = BraftEditor.createEditorState('xxxxxx', { editorId: 'editor-1' })`

在声明使用的时候没有设置`includeEditors`选项，则默认拓展模块对所有editor生效，但依然有上述表格没有出现的问题，这个怎么解决呢。
