### ISSUE TITLE
标题id属性扩展以及控制媒体库问题咨询...

### ISSUE THREAD

**Issue by baby1990** [margox/braft-extensions#3]
当我们写文章时，比如在语雀中，它会自动给h1-h3标题的块加上id属性，这样的话，通过元素类型和id属性，我们可以构造文档页面的锚点，并将页面锚点组织起来形成文档的大纲，对于文档系统来说，这简直是一大利器，非常好用
无奈，才疏学浅，看了Draft.js的默认块的定制，似乎没能找到hack进braft-editor来实现该功能的方法...
希望大神能指点一下解决思路，文档我自己看...

还有，上传图片的时候我希望能在数据库里面记录某文章中所有上传过的图片（文章的图片库），将图片库和组件的媒体库关联起来，这样，媒体库中文件删除时，我这边会按照数据库中记录的图片信息去云端删除该图片，减少无用图片的存储
但目前的问题是，没找到直接插入数据到媒体库的，根据数据库中的图片信息来初始化媒体库的方法...
大神，求指点...

**Comment by margox** [comment]
关于第一点，我这边会去调研一下，尽快支持这个特性。
初始化媒体库内容可以参考[[设置媒体库初始内容]](https://braft.margox.cn/demos/media)这个案例,然后可以通过编辑器内置的hooks监听到媒体库的删除操作，请参阅:[[hooks](https://www.yuque.com/margox/be/gz44tn#gug9gs)]

**Comment by baby1990** [comment]
感激不尽

**Comment by margox** [comment]
@baby1990 刚才更新了一下braft-extensions包，增加了一个标题id扩展模块，你可以试试，实现原理也不难，代码不复杂，你也可以看看

**Comment by baby1990** [comment]
> @baby1990 刚才更新了一下braft-extensions包，增加了一个标题id扩展模块，你可以试试，实现原理也不难，代码不复杂，你也可以看看

破费，我看下咋实现的
