### ISSUE TITLE
表格扩展添加不生效

### ISSUE THREAD

**Issue by Jlanglang** [margox/braft-extensions#57]
![image](https://user-images.githubusercontent.com/17871050/69852135-6c670b00-12be-11ea-85d9-ae14dc9520e5.png)
![image](https://user-images.githubusercontent.com/17871050/69852142-725cec00-12be-11ea-9f6f-7d2ddc10fadd.png)

照着文档设置.发现不生效

**Comment by Jlanglang** [comment]
![image](https://user-images.githubusercontent.com/17871050/69852163-843e8f00-12be-11ea-9e58-e084fd12763f.png)
![image](https://user-images.githubusercontent.com/17871050/69852185-94566e80-12be-11ea-827a-d9c14fa6b4b1.png)

都展示不出来

**Comment by margox** [comment]
use是在render之前么？

**Comment by Jlanglang** [comment]
![image](https://user-images.githubusercontent.com/17871050/69852298-e26b7200-12be-11ea-93bf-508bc25e250f.png)


> 使用是在渲染之前么？
![image](https://user-images.githubusercontent.com/17871050/69852318-e8615300-12be-11ea-9d45-7937cd8404f9.png)

**Comment by margox** [comment]
725634541 加群，这里看不出问题来诶

**Comment by Jlanglang** [comment]
是不是必须引入
![image](https://user-images.githubusercontent.com/17871050/69852682-dfbd4c80-12bf-11ea-9c9f-5012350de260.png)

**Comment by Jlanglang** [comment]
解决了,设置了controls..需要加上'table'.我觉得文档内可以提一下.
