### ISSUE TITLE
编辑有表格的内容时 表格的显示有问题

### ISSUE THREAD

**Issue by lyuehh** [margox/braft-extensions#7]
编辑器里新添加表格没有问题，但是编辑 有表格 的内容时，表格没有正确显示

**Comment by margox** [comment]
关于扩展模块的使用，之前有一个比较重要说明忘记加上了，现在已经补上，你看看：
https://github.com/margox/braft-extensions/blob/master/README.md#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9

**Comment by lyuehh** [comment]
> 关于扩展模块的使用，之前有一个比较重要说明忘记加上了，现在已经补上，你看看：
> https://github.com/margox/braft-extensions/blob/master/README.md#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9

是这个问题，已经好了，多谢~
