### ISSUE TITLE
table功能线条及样式保存问题

### ISSUE THREAD

**Issue by 1261960504** [margox/braft-extensions#8]
在使用表格扩展的时候，editorState.toHTML()转化出来的html代码没有了表格的样式，表格的线条什么的都没有了，请问有什么方法取到对应的html代码吗？包的版本："braft-convert": "^2.1.11","braft-editor": "^2.1.36","braft-extensions": "0.0.13","braft-utils": "^3.0.9"

**Comment by margox** [comment]
参考这个 https://github.com/margox/braft-extensions/issues/7
